libnoise: noise::module::RotatePoint Class Reference
noise::module::RotatePoint Class Reference
Transformer Modules
Noise module that rotates the input value around the origin before returning the output value from a source module.
#include <rotatepoint.h>
Public Member Functions
RotatePoint ()
Constructor.
virtual int GetSourceModuleCount () const
Returns the number of source modules required by this noise module.
virtual double GetValue (double x, double y, double z) const
Generates an output value given the coordinates of the specified input value.
double GetXAngle () const
Returns the rotation angle around the x axis to apply to the input value.
double GetYAngle () const
Returns the rotation angle around the y axis to apply to the input value.
double GetZAngle () const
Returns the rotation angle around the z axis to apply to the input value.
void SetAngles (double xAngle, double yAngle, double zAngle)
Sets the rotation angles around all three axes to apply to the input value.
void SetXAngle (double xAngle)
Sets the rotation angle around the x axis to apply to the input value.
void SetYAngle (double yAngle)
Sets the rotation angle around the y axis to apply to the input value.
void SetZAngle (double zAngle)
Sets the rotation angle around the z axis to apply to the input value.
Public Member Functions inherited from noise::module::Module
Module (int sourceModuleCount)
Constructor.
virtual ~Module ()
Destructor.
virtual const Module & GetSourceModule (int index) const
Returns a reference to a source module connected to this noise module.
virtual void SetSourceModule (int index, const Module &sourceModule)
Connects a source module to this noise module.
Protected Attributes
double m_x1Matrix
An entry within the 3x3 rotation matrix used for rotating the input value.
double m_x2Matrix
An entry within the 3x3 rotation matrix used for rotating the input value.
double m_x3Matrix
An entry within the 3x3 rotation matrix used for rotating the input value.
double m_xAngle
x rotation angle applied to the input value, in degrees.
double m_y1Matrix
An entry within the 3x3 rotation matrix used for rotating the input value.
double m_y2Matrix
An entry within the 3x3 rotation matrix used for rotating the input value.
double m_y3Matrix
An entry within the 3x3 rotation matrix used for rotating the input value.
double m_yAngle
y rotation angle applied to the input value, in degrees.
double m_z1Matrix
An entry within the 3x3 rotation matrix used for rotating the input value.
double m_z2Matrix
An entry within the 3x3 rotation matrix used for rotating the input value.
double m_z3Matrix
An entry within the 3x3 rotation matrix used for rotating the input value.
double m_zAngle
z rotation angle applied to the input value, in degrees.
Protected Attributes inherited from noise::module::Module
const Module ** m_pSourceModule
An array containing the pointers to each source module required by this noise module.
Detailed Description
Noise module that rotates the input value around the origin before returning the output value from a source module.
The GetValue() method rotates the coordinates of the input value around the origin before returning the output value from the source module. To set the rotation angles, call the SetAngles() method. To set the rotation angle around the individual x, y, or z axes, call the SetXAngle(), SetYAngle() or SetZAngle() methods, respectively.
The coordinate system of the input value is assumed to be "left-handed" (x increases to the right, y increases upward, and z increases inward.)
This noise module requires one source module.
Constructor & Destructor Documentation
RotatePoint::RotatePoint ()
Constructor.
The default rotation angle around the x axis, in degrees, is set to noise::module::DEFAULT_ROTATE_X.
The default rotation angle around the y axis, in degrees, is set to noise::module::DEFAULT_ROTATE_Y.
The default rotation angle around the z axis, in degrees, is set to noise::module::DEFAULT_ROTATE_Z.
References noise::module::DEFAULT_ROTATE_X, noise::module::DEFAULT_ROTATE_Y, noise::module::DEFAULT_ROTATE_Z, and SetAngles().
Member Function Documentation
virtual int noise::module::RotatePoint::GetSourceModuleCount () const inline virtual
Returns the number of source modules required by this noise module.
Returns
The number of source modules required by this noise module.
Implements noise::module::Module.
double RotatePoint::GetValue (double x, double y, double z) const virtual
Generates an output value given the coordinates of the specified input value.
Parameters
x The x coordinate of the input value.
y The y coordinate of the input value.
z The z coordinate of the input value.
Returns
The output value.
Precondition
All source modules required by this noise module have been passed to the SetSourceModule() method.
Before an application can call this method, it must first connect all required source modules via the SetSourceModule() method. If these source modules are not connected to this noise module, this method raises a debug assertion.
To determine the number of source modules required by this noise module, call the GetSourceModuleCount() method.
Implements noise::module::Module.
References noise::module::Module::GetValue(), noise::module::Module::m_pSourceModule, m_x1Matrix, m_x2Matrix, m_x3Matrix, m_y1Matrix, m_y2Matrix, m_y3Matrix, m_z1Matrix, m_z2Matrix, and m_z3Matrix.
double noise::module::RotatePoint::GetXAngle () const inline
Returns the rotation angle around the x axis to apply to the input value.
Returns
The rotation angle around the x axis, in degrees.
References m_xAngle.
double noise::module::RotatePoint::GetYAngle () const inline
Returns the rotation angle around the y axis to apply to the input value.
Returns
The rotation angle around the y axis, in degrees.
References m_yAngle.
double noise::module::RotatePoint::GetZAngle () const inline
Returns the rotation angle around the z axis to apply to the input value.
Returns
The rotation angle around the z axis, in degrees.
References m_zAngle.
void RotatePoint::SetAngles (double xAngle, double yAngle, double zAngle)
Sets the rotation angles around all three axes to apply to the input value.
Parameters
xAngle The rotation angle around the x axis, in degrees.
yAngle The rotation angle around the y axis, in degrees.
zAngle The rotation angle around the z axis, in degrees.
The GetValue() method rotates the coordinates of the input value around the origin before returning the output value from the source module.
References noise::DEG_TO_RAD, m_x1Matrix, m_x2Matrix, m_x3Matrix, m_xAngle, m_y1Matrix, m_y2Matrix, m_y3Matrix, m_yAngle, m_z1Matrix, m_z2Matrix, m_z3Matrix, and m_zAngle.
Referenced by RotatePoint(), SetXAngle(), SetYAngle(), and SetZAngle().
void noise::module::RotatePoint::SetXAngle (double xAngle) inline
Sets the rotation angle around the x axis to apply to the input value.
Parameters
xAngle The rotation angle around the x axis, in degrees.
The GetValue() method rotates the coordinates of the input value around the origin before returning the output value from the source module.
References m_yAngle, m_zAngle, and SetAngles().
void noise::module::RotatePoint::SetYAngle (double yAngle) inline
Sets the rotation angle around the y axis to apply to the input value.
Parameters
yAngle The rotation angle around the y axis, in degrees.
The GetValue() method rotates the coordinates of the input value around the origin before returning the output value from the source module.
References m_xAngle, m_zAngle, and SetAngles().
void noise::module::RotatePoint::SetZAngle (double zAngle) inline
Sets the rotation angle around the z axis to apply to the input value.
Parameters
zAngle The rotation angle around the z axis, in degrees.
The GetValue() method rotates the coordinates of the input value around the origin before returning the output value from the source module.
References m_xAngle, m_yAngle, and SetAngles().
Member Data Documentation
double noise::module::RotatePoint::m_x1Matrix protected
An entry within the 3x3 rotation matrix used for rotating the input value.
Referenced by GetValue(), and SetAngles().
double noise::module::RotatePoint::m_x2Matrix protected
An entry within the 3x3 rotation matrix used for rotating the input value.
Referenced by GetValue(), and SetAngles().
double noise::module::RotatePoint::m_x3Matrix protected
An entry within the 3x3 rotation matrix used for rotating the input value.
Referenced by GetValue(), and SetAngles().
double noise::module::RotatePoint::m_y1Matrix protected
An entry within the 3x3 rotation matrix used for rotating the input value.
Referenced by GetValue(), and SetAngles().
double noise::module::RotatePoint::m_y2Matrix protected
An entry within the 3x3 rotation matrix used for rotating the input value.
Referenced by GetValue(), and SetAngles().
double noise::module::RotatePoint::m_y3Matrix protected
An entry within the 3x3 rotation matrix used for rotating the input value.
Referenced by GetValue(), and SetAngles().
double noise::module::RotatePoint::m_z1Matrix protected
An entry within the 3x3 rotation matrix used for rotating the input value.
Referenced by GetValue(), and SetAngles().
double noise::module::RotatePoint::m_z2Matrix protected
An entry within the 3x3 rotation matrix used for rotating the input value.
Referenced by GetValue(), and SetAngles().
double noise::module::RotatePoint::m_z3Matrix protected
An entry within the 3x3 rotation matrix used for rotating the input value.
Referenced by GetValue(), and SetAngles().
The documentation for this class was generated from the following files:
rotatepoint.h
rotatepoint.cpp